//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMX.JobyJobs.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employer_persons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employer_persons()
        {
            this.conversation_messages = new HashSet<conversation_messages>();
            this.employer_person_settings = new HashSet<employer_person_settings>();
            this.reactions = new HashSet<reaction>();
            this.employer_persons_invites = new HashSet<employer_persons_invites>();
        }
    
        public int employer_person_id { get; set; }
        public string identity_user_id { get; set; }
        public int employer_id { get; set; }
        public Nullable<int> employer_department_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string id_number { get; set; }
        public string email { get; set; }
        public string job_function { get; set; }
        public string phone_number { get; set; }
        public System.DateTime register_date { get; set; }
        public bool is_initiator { get; set; }
        public bool active { get; set; }
        public System.DateTime last_update { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<conversation_messages> conversation_messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employer_person_settings> employer_person_settings { get; set; }
        public virtual empoyer_departments empoyer_departments { get; set; }
        public virtual employer employer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reaction> reactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employer_persons_invites> employer_persons_invites { get; set; }
        public virtual user user { get; set; }
    }
}
