//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMX.JobyJobs.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class position_tags
    {
        public int id { get; set; }
        public int position_id { get; set; }
        public string tag_id { get; set; }
        public Nullable<int> precedence { get; set; }
    
        public virtual position position { get; set; }
    }
}
