//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMX.JobyJobs.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class application
    {
        public int id { get; set; }
        public int worker_id { get; set; }
        public int position_id { get; set; }
        public int status_id { get; set; }
        public System.DateTime application_start_date { get; set; }
        public string story { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual position position { get; set; }
    }
}
