//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMX.JobyJobs.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conversation_messages
    {
        public int message_id { get; set; }
        public string message_uid { get; set; }
        public int message_type { get; set; }
        public int worker_id { get; set; }
        public int company_id { get; set; }
        public int company_person_id { get; set; }
        public string header { get; set; }
        public string content { get; set; }
        public System.DateTime date { get; set; }
        public bool is_read { get; set; }
    
        public virtual company company { get; set; }
        public virtual company_persons company_persons { get; set; }
    }
}
