//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMX.JobyJobs.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employer_persons_invites
    {
        public int invite_id { get; set; }
        public string invite_uid { get; set; }
        public int employer_person_id { get; set; }
        public string recipient_email { get; set; }
        public int status_id { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual employer_persons employer_persons { get; set; }
    }
}
