//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMX.JobyJobs.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class extern_cities_languages
    {
        public int city_id { get; set; }
        public int lang_id { get; set; }
        public string visual_name { get; set; }
    
        public virtual extern_cities extern_cities { get; set; }
        public virtual language language { get; set; }
    }
}
