//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMX.JobyJobs.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fields_languages
    {
        public int field_id { get; set; }
        public int lang_id { get; set; }
        public string title { get; set; }
    
        public virtual field field { get; set; }
        public virtual language language { get; set; }
    }
}
