//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMX.JobyJobs.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class interview
    {
        public int interview_id { get; set; }
        public string interview_uid { get; set; }
        public int employer_id { get; set; }
        public Nullable<int> application_id { get; set; }
        public int seeker_id { get; set; }
        public System.DateTime invite_date { get; set; }
        public int invite_status_id { get; set; }
        public string invite_cancelReject_reason { get; set; }
        public System.DateTime due_date { get; set; }
        public string location { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual application application { get; set; }
        public virtual employer employer { get; set; }
        public virtual seeker seeker { get; set; }
    }
}
