//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMX.JobyJobs.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class interview
    {
        public int interview_id { get; set; }
        public string interview_uid { get; set; }
        public int company_id { get; set; }
        public int worker_id { get; set; }
        public System.DateTime date { get; set; }
        public string location { get; set; }
        public string address { get; set; }
        public string notes { get; set; }
        public Nullable<bool> is_cancelled { get; set; }
        public string cancel_reason { get; set; }
    
        public virtual company company { get; set; }
    }
}
