//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMX.JobyJobs.DAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobyJobsDB2 : DbContext
    {
        public JobyJobsDB2()
            : base("name=JobyJobsDB2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_person_settings> admin_person_settings { get; set; }
        public virtual DbSet<admin_persons> admin_persons { get; set; }
        public virtual DbSet<application_statuses> application_statuses { get; set; }
        public virtual DbSet<application> applications { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<company_person_settings> company_person_settings { get; set; }
        public virtual DbSet<company_persons> company_persons { get; set; }
        public virtual DbSet<conversation_messages> conversation_messages { get; set; }
        public virtual DbSet<field> fields { get; set; }
        public virtual DbSet<global_settings> global_settings { get; set; }
        public virtual DbSet<interview> interviews { get; set; }
        public virtual DbSet<position_tags> position_tags { get; set; }
        public virtual DbSet<position> positions { get; set; }
        public virtual DbSet<profession> professions { get; set; }
        public virtual DbSet<reaction_types> reaction_types { get; set; }
        public virtual DbSet<reaction> reactions { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<subprofession> subprofessions { get; set; }
        public virtual DbSet<userclaim> userclaims { get; set; }
        public virtual DbSet<userlogin> userlogins { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<worker_job_interests> worker_job_interests { get; set; }
        public virtual DbSet<worker_resumes> worker_resumes { get; set; }
        public virtual DbSet<worker_settings> worker_settings { get; set; }
        public virtual DbSet<worker> workers { get; set; }
    }
}
