//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMX.JobyJobs.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification_messages_languages
    {
        public int message_id { get; set; }
        public int lang_id { get; set; }
        public string header { get; set; }
        public string content { get; set; }
    
        public virtual language language { get; set; }
        public virtual notification_messages notification_messages { get; set; }
    }
}
