//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMX.JobyJobs.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reaction
    {
        public int id { get; set; }
        public int worker_id { get; set; }
        public int company_id { get; set; }
        public int reaction_type_id { get; set; }
        public bool active { get; set; }
    }
}
