//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMX.JobyJobs.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seeker_job_interests
    {
        public int id { get; set; }
        public int seeker_id { get; set; }
        public Nullable<int> salary_min { get; set; }
        public string location_cities { get; set; }
        public Nullable<int> distance { get; set; }
    
        public virtual seeker seeker { get; set; }
    }
}
